# Site Settings
title: Qi Feng Huang
url: 'http://webjeda.com'
baseurl: '' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6

#Profile information
name: Qi Feng Huang
tagline: Software Engineer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'I am a Software Engineer who loves strawberry cheesecake.'

#sidebar links
email: qifenghuang95@gmail.com
linkedin: qifenghuang
github: qihuang2
facebook: qifeng.huang.12
instagram: major_qi
#Update all the sections by editing the files inside _data folder.

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
